                <td width="50%">
                  <a name="$file$" />
                  <table class="all-pieces">
                    <tr>
                      <td>
                        <a href="/vintage-posters/modern/$file$.html"><img border="0" title="Click for a Detailed View" src="/images/vintage-posters/modern/thumbs/$file$.jpg"></a>
                      </td>
                      <td>
                        <table class="all-pieces-details">
                          <tr><td colspan="2">$title$</td></tr>
                          <tr>
                            <td style="padding-top: 7px;" class="pricetag">
                              \$$price$.00US
                            </td>
                            <td style="padding-top: 7px;">
                              <div class="product">
                                <input value="$title$"
                                       class="product-title"
                                       id="product-title-$id$"
                                       type="hidden">
                                <input value="/images/vintage-posters/modern/$file$.jpg"
                                       class="product-image"
                                       type="hidden">
                                <input value="$price$"
                                       class="product-price"
                                       type="hidden">
                                <img class="googlecart-add" title="Add to Cart" src="/images/cart-all.jpg"/> 
                              </div>
                            </td>
                          </tr>
                          <tr><td style="padding-bottom: 7px;" class="deal" colspan="2"><div class="make-a-deal" id="$id$">make a deal</div></td></tr>
                          <tr><td colspan="2">$authorexpanded$</td></tr>
                          <tr><td colspan="2">$year$</td></tr>
                          <tr><td colspan="2">$size$</td></tr>
                          <tr><td style="padding-top: 5px" colspan="2">$description$</td></tr>
                        </table>
                      </td>
                    </tr>
                  </table>
                </td>
